apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-check
  namespace: network-check
spec:
  selector:
    matchLabels:
      name: network-check
  template:
    metadata:
      labels:
        name: network-check
    spec:
      containers:
        - name: network-check
          image: network-check22
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
        - name: http-echo
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      serviceAccountName: network-check-service-account
      serviceAccount: network-check-service-account

