apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-check-service-account
  namespace: network-check
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: network-check
  name: network-check-role
rules:
  - apiGroups: [ "", "apps" ]
    resources: [ "pods", "daemonsets" ]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-check-rolebinding
  namespace: network-check
subjects:
  - kind: ServiceAccount
    name: network-check-service-account
    namespace: network-check
roleRef:
  kind: Role
  name: network-check-role
  apiGroup: rbac.authorization.k8s.io